format = """
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$pijul_channel\
$nats\
$direnv\
$env_var\
$mise\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

palette = "terafox"

[palettes.terafox]
red = "#e85c51"
green = "#7aa4a1"
purple = "#ad5c7c"
yellow = "#fda47f"
os_bg = "#587b7b"
os_fg = "#0f1c1e"
dir_bg = "#7aa4a1"
dir_fg = "#152528"
git_bg = "#fda47f"
git_fg = "#1d3337"
lang_bg = "#5a93aa"
lang_fg = "#254147"

[custom.jj]
description = "The current jj status"
format = "[ $symbol$output ]($style) "
when = "jj --ignore-working-copy root"
symbol = "🥋 "
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    "|",
    concat(
      if(conflict, "💥"),
      if(divergent, "🚧"),
      if(hidden, "👻"),
      if(immutable, "🔒"),
    ),
    raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
    raw_escape_sequence("\x1b[1;32m") ++ coalesce(
      truncate_end(16, description.first_line(), "…"),
      "(no desc)",
    ) ++ raw_escape_sequence("\x1b[0m"),
  )
'
'''

# optionally disable git modules when JJ is found.
# note that you'll need to add ${custom.git_branch}, ${custom.git_commit} etc
# into format: https://starship.rs/config/#default-prompt-format
[git_status]
disabled = true

[custom.git_status]
when = "! jj --ignore-working-copy root"
command = "starship module git_status"
description = "Only show git_status if we're not in a jj repo"

[git_commit]
disabled = true

[custom.git_commit]
when = "! jj --ignore-working-copy root"
command = "starship module git_commit"
description = "Only show git_commit if we're not in a jj repo"

[git_metrics]
disabled = true

[custom.git_metrics]
when = "! jj --ignore-working-copy root"
command = "starship module git_metrics"
description = "Only show git_metrics if we're not in a jj repo"

[git_branch]
disabled = true

[custom.git_branch]
style = "fg:git_bg"
when = "! jj --ignore-working-copy root"
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"

[directory]
style = "fg:dir_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "../"

